### ISSUE TITLE
cannot open camera

### ISSUE THREAD

**Issue by Romyull-Islam** [blikoon/QRCodeScanner#11]
when I run the project it shows cannot open camera

**Comment by rutura** [comment]
You need to provide camera permissions to the App before you open the activity : https://github.com/blikoon/QRCodeScanner/issues/5 
If you do it for you App, PRs are welcome to integrate that in the library. Help needed : https://github.com/blikoon/QRCodeScanner/issues/7

**Comment by guttulasai** [comment]
Thanks for the info!!

**Comment by nehagote** [comment]
I was facing the same issue adding Vibrate permission along with camera resolved my issue.
