### ISSUE TITLE
cannot run on my phone

### ISSUE THREAD

**Issue by guttulasai** [blikoon/QRCodeScanner#17]
hie..

i m sorry but i could not run this code on my phone..
it gives me a notification saying 'Could not open your camera'

**Comment by rutura** [comment]
Duplicate of https://github.com/blikoon/QRCodeScanner/issues/11 .
Closing this.

**Comment by nehagote** [comment]
I was facing the same issue adding Vibrate permission along with camera resolved my issue.
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.CAMERA" />
