### ISSUE TITLE
library not working

### ISSUE THREAD

**Issue by mahdiyousofun** [blikoon/QRCodeScanner#6]
hi 
i use compile 'com.github.blikoon:QRCodeScanner:0.1.2' in my project
but android studio couldnt solve this library.

**Comment by rutura** [comment]
Hi,
Is logcat inside Android Studio giving any output ? My wild guess is android studio is failing to connect to jitpack for some reason.

**Comment by ALMSTJSON** [comment]
Did you try to re-sync the project with your gradle files?
